nome = input('Digite seu nome: ')
print('Seu nome em maiúsculas é',(nome.upper()))
print('Seu nome em minúsculas é',(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)))
print('A primeira palavra tem {} letras'.format(nome.find(' ')))